spring:
  application:
    name: 10tteockgi
  profiles:
    active: dev  # ?????? application-dev.yml ? ????? ??
    include: secret # active ?? ???? (application-dev.yml) ??? application-secret.yml ? ????? ??
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Lazy ??? ? ? ??? DB?? ???? ???? ?
        show_sql: true # SQL ??? ?? ?? ???
        format_sql: true # SQL ??? ?????
        use_sql_comments: true # SQL ??? ???
  logging:
    level:
      # SQL? ??? ?? ????, SQL? ??? ??
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE