server:
  port: 8030
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/10tteockgi_dev
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop